filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
    javascript:
        code_rating: false
coding_style:
    php: {  }
build: true
