language: php
php:
  - 7.0
  - 7.1
before_install:
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - sbr
